name: bignumbers
description: Big numbers library for Dart, supporting arbitrary precision arithmetic.
version: 0.0.1-beta
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
